name: CI on Specific Label

on:
  issues:
    types: [labeled]

jobs:
  developer:
    runs-on: [developer]
    if: github.event.label.name == 'testing'
    env:
      ISSUE_NUMBER: ${{ github.event.issue.number }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show issue content
        run: |
          gh issue view "$ISSUE_NUMBER" --repo "$GITHUB_REPOSITORY" \
            --json number,title,body --jq '.'
