name: CI on Specific Label

on:
  issues:
    types: [labeled]

jobs:
  job-marketing:
    runs-on: [self-hosted, developer]
    if: github.event.label.name == 'testing'
    container:
      image: localhost:5001/ci-runner:v1
    env:
      ISSUE_NUMBER: ${{ github.event.issue.number }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show issue content
        run: |
          gh issue view $ISSUE_NUMBER --repo $GITHUB_REPOSITORY \
            --json number,title,body --jq '.'
