name: CI on Specific Label

on:
  issues:
    types: [labeled]

jobs:
  developer:
    runs-on: [developer]
    if: github.event.issue.state == 'open' && github.event.issue.locked == false
    env:
      ISSUE_NUMBER: ${{ github.event.issue.number }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Plandex workflow
        run: ./scripts/run-plandex.sh
