name: Test Fly Runner

on:
  issues:
    types: [labeled]

jobs:
  hello:
    runs-on: [self-hosted, dind]
    container:
      image: alpine:3.19
    steps:
      - run: echo "Hello from Fly.io runner!"
