name: CI on Specific Label

on:
  issues:
    types: [labeled]

jobs:
  developer:
    runs-on: [developer]

    if: github.event.issue.state == 'open' && github.event.issue.locked == false

    env:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      PLANDEX_TOKEN: ${{ secrets.PLANDEX_TOKEN }}
      PLANDEX_HOST: ${{ secrets.PLANDEX_HOST }}
      PLANDEX_SKIP_CLAUDE_PROMPT: ${{ secrets.PLANDEX_SKIP_CLAUDE_PROMPT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Init & dev Plandex
        run: |
          export
          plandex models custom -f /actions-runner/config/anthropic-models.json --save
          plandex set-model anthropic-blend
          
