name: Test Runner

on:
  issues:
    types: [labeled]
jobs:
  hello:
    runs-on: [self-hosted, developer]
    container:
      image: alpine:3.19
    steps:
      - name: Say hello
        run: echo "Hello from inside the container!"
